# Generated by Django 5.2.3 on 2025-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "наличные"),
                    ("transfer_to_account", "перевод на счет"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
