# Generated by Django 5.2.3 on 2025-06-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата и время платежа"
            ),
        ),
    ]
