# Generated by Django 5.2.3 on 2025-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.FloatField(
                help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"
            ),
        ),
    ]
