# Generated by Django 5.2.3 on 2025-07-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите сумму оплаты",
                max_digits=10,
                verbose_name="Сумма оплаты",
            ),
        ),
    ]
