# Generated by Django 5.2.3 on 2025-07-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_owner_lesson_owner"),
        ("users", "0009_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subscription_course",
            new_name="course",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course")},
        ),
    ]
