services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

  db:
    image: postgres
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
        interval: 30s
        timeout: 10s
        retries: 5

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A config worker -l INFO -P eventlet
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_HOST=db
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: celery -A config beat -l INFO
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_HOST=db
    depends_on:
      - redis
      - db

networks:
  default:

volumes:
  postgres_data:
  static_volume:
  redis_data:
