# Generated by Django 5.2.3 on 2025-06-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_video",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                max_length=150,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
